### ISSUE TITLE
Include the last move in solution output after completion of the level

### ISSUE THREAD

**Issue by ckjr** [nginyc/Magna-Caves#68]
In the future, where there might be multiple treasure tiles, there is a need to include those extra taps when getting any treasure tile.

**Comment by nginyc** [comment]
This should be resolved - double check

**Comment by ckjr** [comment]
Those extra taps are still not registered though. I tried this in the latest commit.

**Comment by nginyc** [comment]
Oops, should be fixed in this commit
